@extends('layouts.index')
@section('content')
    <div class="hero">
        <div class="container">
            <div class="row justify-content-between">
                <div class="col-lg-5">
                    <div class="intro-excerpt">
                        <h1>Harga Murah <span clsas="d-block">& Terjangkau</span></h1>
                        <p class="mb-4">Nikmati berbagai kemudahan yang didesain khusus untuk Anda mulai dari pilih
                            paket, atur tagihan, hingga pembayaran </p>
                        <p><a href="{{ route('produk') }}" class="btn btn-secondary me-2">Belanja Sekarang</a></p>
                    </div>
                </div>
                <div class="col-lg-7">
                    <div class="hero-img-wrap">
                        <img src="{{ asset('furni/images/provider.png') }}" class="img-fluid">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End Hero Section -->

    <!-- Start Product Section -->
    <div class="product-section">
        <div class="container">
            <div class="row">

                <!-- Start Column 2 -->

                @foreach ($barang as $v)
                    <!-- Start Column (Generated by Loop) -->
                    <div class="col-12 col-md-4 col-lg-3 mb-5 mb-md-0">
                        <a class="product-item" href="cart.html">
                            <img src="{{ asset('img/barang/' . $v->gambar) }}" class="img-fluid product-thumbnail">
                            <h3 class="product-title">{{ $v->nama_barang }}</h3>
                            <strong class="product-price"></strong>

                            <span class="icon-cross">
                                <img src="{{ asset('furni/images/cross.svg') }}" class="img-fluid">
                            </span>
                        </a>
                    </div>
                    <!-- End Column (Generated by Loop) -->
                @endforeach
                <!-- End Column 4 -->

            </div>
        </div>
    </div>
@endsection
@push('scripts')
    <script>
        // $(document).ready(function() {
        //     // $('#modalID').modal('show');
        //     // $.noConflict();



        //     $.ajaxSetup({
        //         headers: {
        //             'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        //         }
        //     });
        // });
        // document.addEventListener('DOMContentLoaded', function() {
        //     var openModalButtons = document.querySelectorAll('.open-modal');
        //     openModalButtons.forEach(function(button) {
        //         button.addEventListener('click', function() {
        //             var productName = button.closest('.product-box').querySelector('h3')
        //                 .textContent;
        //             var productPrice = button.closest('.product-box').querySelector('span')
        //                 .textContent;
        //             var barangId = button.closest('.product-box').querySelector('h6')
        //                 .textContent; // Extract text content

        //             // Set modal content based on the extracted information
        //             var modalProductName = document.getElementById('modalProductName');
        //             var modalProductPrice = document.getElementById('modalProductPrice');
        //             var modalProductId = document.getElementById('modalProductId');

        //             modalProductName.textContent = 'Barang : ' + productName;
        //             modalProductPrice.textContent = 'Harga : ' + productPrice;
        //             modalProductId.value =
        //                 barangId; // Set the value of the input instead of text content

        //             // Show the modal
        //             $('#exampleModal').modal('show');
        //         });
        //     });



        //     // $('#exampleModal').on('hidden.bs.modal', function() {
        //     //     $('.modal-backdrop').remove();
        //     //     // location.reload();
        //     // });
        // });

        // $('#form').on('submit', function(event) {
        //     event.preventDefault();
        //     var formData = new FormData(this);
        //     console.log(formData.get('product_id'));
        //     // var id = $('#data_id').val();
        //     var url = "{{ route('addKeranjang') }}";
        //     // if (id != '') {
        //     //     //kirim id lewat form data 
        //     //     formData.append('data_id', id);
        //     // }
        //     $.ajax({
        //         url: url,
        //         method: "POST",
        //         data: formData,
        //         contentType: false,
        //         cache: false,
        //         processData: false,
        //         dataType: "json",
        //         success: function(data) {
        //             console.log(data);
        //             if (data.status == 'success') {
        //                 Swal.fire({
        //                     position: 'center',
        //                     icon: 'success',
        //                     title: 'Berhasil',
        //                     showConfirmButton: false,
        //                     timer: 1500
        //                 })
        //             } else {
        //                 Swal.fire({
        //                     position: 'center',
        //                     icon: 'error',
        //                     title: 'Gagal',
        //                     showConfirmButton: false,
        //                     timer: 1500
        //                 })
        //             }


        //         },
        //         error: function(data) {
        //             console.log(data);


        //         }
        //     })
        //     $('#exampleModal').modal('hide');
        //     // $("#exampleModal").removeClass("in");
        //     $(".modal-backdrop").remove();
        //     // $("#exampleModal").hide();
        // });


        // // function addToCart() {
        // //     var productName = document.getElementById('modalProductName').textContent;
        // //     var productPrice = document.getElementById('modalProductPrice').textContent;
        // //     var barangId = document.getElementById('modalProductId').value;

        // // alert('Product added to cart!\n' + productName + '\nHargav: ' + productPrice +
        // //     '\nBarang IDv: ' + barangId);

        // // TODO: Send a POST request to your server with the data (productName, productPrice, quantity, barangId)
        // // Example using fetch:


        // // }
    </script>
@endpush
