@extends('layouts.index')
@section('content')
    <div class="hero">
        <div class="container">
            <div class="row justify-content-between">
                <div class="col-lg-5">
                    <div class="intro-excerpt">
                        <h1>Harga Murah <span clsas="d-block">& Terjangkau</span></h1>
                        <p class="mb-4">Nikmati berbagai kemudahan yang didesain khusus untuk Anda mulai dari pilih
                            paket, atur tagihan, hingga pembayaran </p>
                        <p><a href="{{ route('produk') }}" class="btn btn-secondary me-2">Belanja Sekarang</a></p>
                    </div>
                </div>
                <div class="col-lg-7">
                    <div class="hero-img-wrap">
                        <img src="{{ asset('furni/images/provider.png') }}" class="img-fluid">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End Hero Section -->

    <!-- Start Product Section -->
    <div class="product-section">
        <div class="container">
            <div class="row">

                @foreach ($barang as $v)
                    <!-- Start Column (Generated by Loop) -->
                    <div class="col-12 col-md-4 col-lg-3 mb-5 mb-md-0">
                        <a class="product-item" href="{{ route('addKeranjang', $v->id) }}">
                            <img src="{{ asset('img/barang/' . $v->gambar) }}" class="img-fluid product-thumbnail">
                            <h3 class="product-title">{{ $v->nama_barang }}</h3>
                            <h3 class="product-title">Tersedia : {{ $v->stok }}</h3>
                            
                            <strong class="product-price"></strong>

                            <span class="icon-cross">
                                <img src="{{ asset('furni/images/cross.svg') }}" class="img-fluid">
                            </span>
                        </a>
                    </div>
                    <!-- End Column (Generated by Loop) -->
                @endforeach
                <!-- End Column 4 -->

            </div>
        </div>
    </div>
@endsection
@push('scripts')
    <script>
        
    </script>
@endpush
