@extends('layouts.index')
@section('content')
    <div class="hero">
        <div class="container">
            <div class="row justify-content-between">
                <div class="col-lg-5">
                    <div class="intro-excerpt">
                        <h1>Produk</h1>
                    </div>
                </div>
                <div class="col-lg-7">

                </div>
            </div>
        </div>
    </div>
    <div class="product-section">
        <div class="container">
            <div class="row">

                @foreach ($barang as $v)
                    <!-- Start Column (Generated by Loop) -->
                    <div class="col-12 col-md-4 col-lg-3 mb-5 mb-md-0">
                        <a class="product-item" href="{{ route('addKeranjang', $v->id) }}">
                            <img src="{{ asset('img/barang/' . $v->gambar) }}" class="img-fluid product-thumbnail">
                            <h3 class="product-title">{{ $v->nama_barang }}</h3>
                            <h3 class="product-title">Tersedia : {{ $v->stok }}</h3>
                            <strong class="product-price"></strong>

                            <span class="icon-cross">
                                <img src="{{ asset('furni/images/cross.svg') }}" class="img-fluid">
                            </span>
                        </a>
                    </div>
                    <!-- End Column (Generated by Loop) -->
                @endforeach
                <!-- End Column 4 -->

            </div>
        </div>
    </div>
@endsection
@push('scripts')
    <script>
        $(document).ready(function() {
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            // Initialize total
            let total = 0;
            let harga = [];
            let jumlah = [];

            // Update total when a checkbox is checked or unchecked
            $('input[name="check[]"]').change(function() {
                total = 0;

                // Loop through checked checkboxes and update total
                $('input[name="check[]"]:checked').each(function() {
                    // get harga and quantity from name harga[] and jumlah[]
                    let price = $(this).closest('.row').find('input[name="harga[]"]').val();
                    let quantity = $(this).closest('.row').find('input[name="jumlah[]"]').val();
                    console.log('Price:', price, 'Quantity:', quantity);

                    // Try to parse as a float
                    price = parseFloat(price.replace('Rp ', '').replace(',', ''));

                    if (!isNaN(price)) {

                        // Multiply the price by quantity and add to the total
                        total += price * quantity;
                    } else {
                        console.error('Invalid price:', $(this).closest('.row').find(
                            '.text-center h3').text());
                    }
                });
                console.log(total);
                $('#total').val(total);
                // Update the totalBayar element
                $('#totalBayar').text(total);

                // Log the total whenever it changes
                console.log('Total:', total);
            });

            console.log(total);
            $('#form').on('submit', function(event) {
                event.preventDefault();
                let formData = new FormData(this);
                let cek = $('input[name="check[]"]:checked').length;
                console.log(cek);
                if (cek > 0) {
                    formData = formData;
                    console.log(cek);
                    console.log(formData);
                    // } else if (cek > 1) {
                    //     console.log(cek);
                    //     $('input[name="check[]"]:checked').each(function() {
                    //         formData.append('check[]', $(this).val());
                    //     });
                } else {
                    formData = null;
                    console.log('No checkboxes are checked.');
                }
                // formData = barang_id;
                var url = "{{ route('pesan') }}";

                $.ajax({
                    url: url,
                    method: "POST",
                    data: formData,
                    contentType: false,
                    cache: false,
                    processData: false,
                    dataType: "json",
                    success: function(data) {
                        console.log(data);
                        if (data.status == 'success') {
                            Swal.fire({
                                position: 'center',
                                icon: 'success',
                                title: 'Berhasil',
                                showConfirmButton: false,
                                timer: 1500
                            })
                        } else {
                            Swal.fire({
                                position: 'center',
                                icon: 'error',
                                title: 'Gagal',
                                showConfirmButton: false,
                                timer: 1500
                            })
                        }


                    },
                    error: function(data) {
                        console.log(data);


                    }
                })
                $('#exampleModal').modal('hide');
                // $("#exampleModal").removeClass("in");
                $(".modal-backdrop").remove();
                // $("#exampleModal").hide();
            });
        })
    </script>
@endpush
